### ISSUE TITLE
Cannot find module "node:events"

### ISSUE THREAD

**Issue by MineJulRBX** [jozsefsallai/discord.js-minesweeper#16]
![image](https://user-images.githubusercontent.com/34965273/136361049-db705c6a-2712-42e1-90e9-ab7daecd66c5.png)

**Comment by jozsefsallai** [comment]
I am going to assume you're using discord.js v13, which requires you to use Node.js v16. Either downgrading your discord.js or upgrading your Node.js should fix the issue. This problem is not related to discord.js-minesweeper.
