### ISSUE TITLE
Might have some algo issue

### ISSUE THREAD

**Issue by adan-ea** [jozsefsallai/discord.js-minesweeper#17]
When i generate a minesweeper it just goes this way for some reason.
![image](https://user-images.githubusercontent.com/57812567/148360388-c48f26e6-5dbb-4664-a42b-87145e086c8f.png)

How i generate the minesweeper in my code (i use discord akairo, it might break something ?): 

```js
const minesweeper = new Minesweeper({
            rows: rows,
            columns: columns,
            mines: mines,
            emote: 'boom',
        });
        minesweeper.start();

        const matrix = minesweeper.start();
```

**Comment by jozsefsallai** [comment]
You mean this is always your output? Or just very similar to this?

The algorithm used for planting the mines is a very simple random number generator. So if you always get the same or similar results, it means either:

- your `Math.random` is overwritten by another function
- your Node's random number generator is broken or improperly seeded
- you have some really wacky luck

Try running this before the generation and show me the matrix it produces:

```js
const matrix = new Array(7).fill(null).map(e => new Array(9).fill(0));

for (let i = 0; i < 30; i++) {
  const x = Math.floor(Math.random() * 7);
  const y = Math.floor(Math.random() * 9);

  if (matrix[x][y] === 1) {
    i--;
  } else {
    matrix[x][y] = 1;
  }
}
```

**Comment by adan-ea** [comment]
I'm having really similar results, every bomb on the top with way too many rows.
I do have bad luck but this time i'm almost sure it's not it

Here : 
![image](https://user-images.githubusercontent.com/57812567/148730156-046d48f5-0c4e-41d7-a33c-b39f3d0afefa.png)
![image](https://user-images.githubusercontent.com/57812567/148731051-0ff97410-2269-4262-a2e7-71f8c421bc3d.png)

**Comment by jozsefsallai** [comment]
The output seems normal to me here.

To be honest what weirds me out even more is that you asked for 7 rows and you somehow got 11 instead... I honestly haven't ever seen anything like this before.

Have you tried uninstalling and reinstalling the module? Also can you show me the full akairo command file?
FYI I'm using akairo + discord.js-minesweeper too in my bot and it works fine, so I doubt that's the problem. Here's the code I have anyway: https://github.com/thimble-bot/thimble-bot/blob/master/src/commands/fun/minesweeper.ts

**Comment by jozsefsallai** [comment]
Oh, I think I just realized what you're doing wrong! You're calling `minesweeper.start();` twice, so it tries to repopulate the matrix twice as well, which results in undefined behavior like this.

**Comment by adan-ea** [comment]
Ooh... right, i'm so sorry i opened an issue for this.. Sorry for the waste of time !
